# Question 1

In [27]:
import numpy as np
arr = np.arange(2,51,3).tolist()
print(arr)

[2, 5, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50]


# Question 2

In [15]:
list1 = []
print("Enter Elements for List 1 :-")
for i in range(0,5):
    x = int(input())
    list1.append(x)


list2 = []
print("Enter Elements for List 2 :-")
for f in range(0,5):
    y = int(input())
    list2.append(y)
print("Two Lists Entered are :-")
print(list1)
print(list2)
print("")
import numpy as np
np1 = np.array(list1)
np2 = np.array(list2)
print("Two Arrays are :-")
print(np1)
print(np2)
print("")
con = np.concatenate((np1,np2))
print("Concatenated Array is :-")
print(con)
print("")
sort = np.sort(con)
print("Sorted Array is :-")
print(sort)

Enter Elements for List 1 :-
1
2
3
4
5
Enter Elements for List 2 :-
6
7
8
9
0
Two Lists Entered are :-
[1, 2, 3, 4, 5]
[6, 7, 8, 9, 0]

Two Arrays are :-
[1 2 3 4 5]
[6 7 8 9 0]

Concatenated Array is :-
[1 2 3 4 5 6 7 8 9 0]

Sorted Array is :-
[0 1 2 3 4 5 6 7 8 9]


# Question 3

In [14]:
import numpy as np
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
print("")
print("The dimension of above array is :  " + str(arr1.ndim))
print("")
print("The size of above string is :   " + str(arr1.size))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

The dimension of above array is :  2

The size of above string is :   9


# Question 4

In [19]:
import numpy as np
arr2 = np.random.rand(5,)
print(arr2.ndim)
arr3 = arr2[np.newaxis , :]
print(arr3.ndim)


1
2


# Question 5 

In [24]:
import numpy as np
arr1 = np.random.rand(3,3)
arr2 = np.random.rand(3,3)
print(np.vstack((arr1,arr2)))
print()
print(np.hstack((arr1,arr2)))

[[0.60418892 0.79721024 0.32485085]
 [0.43718812 0.53938487 0.49011419]
 [0.44712414 0.41907165 0.90601531]
 [0.42692718 0.54179271 0.84828492]
 [0.31127874 0.46070019 0.19093921]
 [0.99400198 0.39894116 0.24550118]]

[[0.60418892 0.79721024 0.32485085 0.42692718 0.54179271 0.84828492]
 [0.43718812 0.53938487 0.49011419 0.31127874 0.46070019 0.19093921]
 [0.44712414 0.41907165 0.90601531 0.99400198 0.39894116 0.24550118]]


# Question 6

In [26]:
import numpy as np
arr = np.array([1,2,6,4,7,2,7,8,5,4,6,8,7,4,2,5,0,6,4,8,2,9,2])
print(np.unique(arr, return_counts=True))

(array([0, 1, 2, 4, 5, 6, 7, 8, 9]), array([1, 1, 5, 4, 2, 3, 3, 3, 1], dtype=int64))
